@startuml 预测试流程图

start

if(校验用例是否存在,用例下是否存在步骤？)then(yes-开始执行测试)
    :删除前一次预测试结果;
    while(遍历用例下步骤集合,未遍历完毕?)
        :准备请求数据;
        :发起 HTTP OR SQL 请求;
        :处理请求结果,校验后入库;
    endwhile
    :计算测试总计用时;
    :校验测试成功失败,响应给前端;
else(No-返回执行异常信息)
    :响应执行失败异常信息给前端;
endif
stop

@enduml
